environment:
  matrix:
  - nodejs_version: "0.10"
  - nodejs_version: "0.12"
  - nodejs_version: "4"
  - nodejs_version: "5"
  - nodejs_version: "6"
  webp_version: "0.5.0"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - ps: .\bin\download_webp.ps1

test_script:
  - cwebp -version
  - node --version
  - npm --version
  - npm test

build: off
